# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58faff14e68f239d45d0cbece1b03cfdc239550a6be49018a11c6834d0c36c4998c6e0c52e6a22210f5158377a3f22acc3eae7451c259f949e671e5900d812e3

test:
  secret_key_base: 5c2094577e89d2cb352b750995b4b2b609ec69d93f6acb2205409c6d4584056a2c237276549aae67607f92af62f59555375d12f09587b2b1b47fac0bf8e97dc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
